services:
  mapaztm:
    image: ghcr.io/bartekl1/mapa-ztm:latest
    container_name: mapa-ztm
    restart: unless-stopped
    environment:
      GUNICORN_WORKERS: 4
    ports:
      - 127.0.0.1:8000:8080
    volumes:
      # - ./config.yaml:/app/config.yaml:ro
      - cache:/app/cache
      # - ./cache:/app/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  cache:
